# Generated by Django 4.1.5 on 2023-01-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
