# Generated by Django 4.1.5 on 2023-01-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_brand_rename_discount_product_discounted_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="age_group",
            field=models.CharField(
                blank=True,
                choices=[("kids", "Kids"), ("adults", "Adults")],
                max_length=10,
                null=True,
            ),
        ),
    ]
