# Generated by Django 4.1.5 on 2023-01-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_subcategory"),
        ("products", "0006_product_age_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                related_name="product", to="categories.category"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sub_category",
            field=models.ManyToManyField(
                related_name="product", to="categories.subcategory"
            ),
        ),
    ]
